---
abstract: 'fast MVC-style Apache2 handler apps'
author:
  - 'Mark Hedges <hedges@formdata.biz>'
build_requires:
  Apache::Test: 1.12
  Apache::TestMM: 0
  Apache::TestRequest: 0
  Apache::TestRunPerl: 0
  Apache::TestUtil: 0
  HTTP::Cookies: 0
  LWP: 0
  Math::BigInt::GMP: 0
  URI::Escape: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Apache2-Controller
provides:
  Apache2::Controller:
    file: lib/Apache2/Controller.pm
    version: v1.1.0
  Apache2::Controller::Auth::OpenID:
    file: lib/Apache2/Controller/Auth/OpenID.pm
    version: v1.1.0
  Apache2::Controller::Const:
    file: lib/Apache2/Controller/Const.pm
    version: v1.1.0
  Apache2::Controller::DBI::Connector:
    file: lib/Apache2/Controller/DBI/Connector.pm
    version: v1.1.0
  Apache2::Controller::Directives:
    file: lib/Apache2/Controller/Directives.pm
    version: v1.1.0
  Apache2::Controller::Dispatch:
    file: lib/Apache2/Controller/Dispatch.pm
    version: v1.1.0
  Apache2::Controller::Dispatch::HashTree:
    file: lib/Apache2/Controller/Dispatch/HashTree.pm
    version: v1.1.0
  Apache2::Controller::Dispatch::RenderTemplate:
    file: lib/Apache2/Controller/Dispatch/RenderTemplate.pm
    version: v1.1.0
  Apache2::Controller::Dispatch::Simple:
    file: lib/Apache2/Controller/Dispatch/Simple.pm
    version: v1.1.0
  Apache2::Controller::Funk:
    file: lib/Apache2/Controller/Funk.pm
    version: v1.1.0
  Apache2::Controller::Log::DetectAbortedConnection:
    file: lib/Apache2/Controller/Log/DetectAbortedConnection.pm
    version: v1.1.0
  Apache2::Controller::Log::SessionSave:
    file: lib/Apache2/Controller/Log/SessionSave.pm
    version: v1.1.0
  Apache2::Controller::Methods:
    file: lib/Apache2/Controller/Methods.pm
    version: v1.1.0
  Apache2::Controller::NonResponseBase:
    file: lib/Apache2/Controller/NonResponseBase.pm
    version: v1.1.0
  Apache2::Controller::NonResponseRequest:
    file: lib/Apache2/Controller/NonResponseRequest.pm
    version: v1.1.0
  Apache2::Controller::PerChildInit:
    file: lib/Apache2/Controller/PerChildInit.pm
    version: v1.1.0
  Apache2::Controller::Render::Template:
    file: lib/Apache2/Controller/Render/Template.pm
    version: v1.1.0
  Apache2::Controller::SQL::MySQL:
    file: lib/Apache2/Controller/SQL/MySQL.pm
    version: v1.1.0
  Apache2::Controller::Session:
    file: lib/Apache2/Controller/Session.pm
    version: v1.1.0
  Apache2::Controller::Session::Cookie:
    file: lib/Apache2/Controller/Session/Cookie.pm
    version: v1.1.0
  Apache2::Controller::X:
    file: lib/Apache2/Controller/X.pm
    version: v1.1.0
recommends:
  IPC::Open3: 0
  LWPx::ParanoidAgent: 0
requires:
  Apache2::CmdParms: 0
  Apache2::Connection: 0
  Apache2::Const: 0
  Apache2::Cookie: 0
  Apache2::Directive: 0
  Apache2::Module: 0
  Apache2::Request: 0
  Apache2::RequestIO: 0
  Apache2::RequestRec: 0
  Apache2::RequestUtil: 0
  Apache::Session: 0
  Apache::Session::File: 0
  DateTime: 0
  Digest::SHA: 0
  English: 0
  Exception::Class: 0
  ExtUtils::MakeMaker: 0
  File::Spec: 0
  File::Temp: 0
  FindBin: 0
  HTTP::Status: 0
  List::MoreUtils: 0
  Log::Dispatch: 0
  Log::Log4perl: 0
  Net::OpenID::Consumer: 0
  Net::OpenID::Server: 0
  Readonly: 0
  Scalar::Util: 0
  Template: 0
  Test::More: 0
  URI: 0
  YAML::Syck: 0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: v1.1.0
